In [1]:
#In the first example we did on 2.1 chapter, we created a neural network by stacking dense layers
#keras.layers.Dense(512, activation='relu')

"""
This layer can be interpretted as a function that takes 2D tensor as an input and returns another 2D tensor, which is a new 
representation of input tensor. Specifically, this function is like this: output = relu(dot(W, input) + b) where W is 2D tensor, and b
is a vector.

Below are three tensor operations: dot operation between input tensor and tensor W, addition between 2D tensor which is a result of dot
operation and vector b, and relu. relu(x) is equivalent to max(x, 0)

Relu function and addition is element-wise operation. Element-wise operation is applied on each elements in tensor independently.
"""

def naive_relu(x):
    assert len(x.shape) == 2
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

def naive_add(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

import numpy as np

#addition
#z = x + y

#relu function
#z = np.maximum(z, 0.)

"""
If you try to add two tensors with different size, broadcasting occurs. Broadcasting consists of two steps:
1. Axis are added to "small" tensor so that small tensor's ndim matches that of big tensor
2. Small tensor is then replicated across the new axis to match the size of big tensor

For example, suppose that we are trying to do:
[[1, 2, 3],  +  [7, 8, 9]
 [4, 5, 6]]

To compute this, we need to broadcast the latter tensor like this:
[[1, 2, 3],  +  [[7, 8, 9],
 [4, 5, 6]]      [7, 8, 9]]

In implementing this, if actually new tensor is created in the process, it would be very inefficient. Therefore, this new 2D tensor
after broadcasting is not actually created in memory.
"""

def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

#You can apply broadcasting to (a,b,...,m,...,n) size tensor and (m,...,n) size tensor. Broadcasting occurs at a to n-1 axis.

import numpy as np

x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))

z = np.maximum(x, y)

"""
Dot operation, aka tensor product, is widely used tensor operation.
"""

#import numpy as np
#z = np.dot(x,y)

#Dot operation between two vectors
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

#Dot operation between one matrix and one vector
def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0]) #This creates vector with same size as x, with elements all zeros
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

"""
We can also write this as:

def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)
    return z
"""

def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

"""
Tensor reshaping is restructing the row and column of the tensor. Reshaped tensor has same number of elements with the original's.
"""

#Example of tensor reshaping
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])
print(x.shape)
x = x.reshape((6, 1))
print(x)
x = x.reshape((2, 3))
print(x)

#Frequently used tensor reshaping is transposition. It changes row and column. In other words, x[i, :] becomes x[:, i] and vice versa.
x = np.zeros((300, 20))
x = np.transpose(x)
print(x.shape)

(3, 2)
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[0. 1. 2.]
 [3. 4. 5.]]
(20, 300)
